apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-worker
  labels:
    app: rag-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-worker
  template:
    metadata:
      labels:
        app: rag-worker
    spec:
      containers:
      - name: worker
        image: orhunkupeli/rag-worker:v1
        imagePullPolicy: Always
        env:
          - name: RABBITMQ_HOST
            value: "rabbitmq.default.svc.cluster.local"
          - name: RABBITMQ_USER
            value: "user"
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RABBITMQ_PASS

          - name: S3_ENDPOINT
            value: "http://seaweedfs-s3.default.svc.cluster.local:8333"
          - name: S3_BUCKET
            value: "documents"
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: S3_SECRET_KEY

          - name: QDRANT_HOST
            value: "qdrant.default.svc.cluster.local"
          - name: QDRANT_PORT
            value: "6333"